### ISSUE TITLE
Crash on server start with dynamic render distance

### ISSUE THREAD

**Issue by boasbakker** [QuiltServerTools/TickTools#4]
Sercer crashes when starting:
[10:17:52] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_3218.method_14178()" because the return value of "net.minecraft.server.MinecraftServer.method_30002()" is null
	at com.github.quiltservertools.ticktools.TickToolsConfig.readToml(TickToolsConfig.java:76) ~[ticktools-1.0.0.jar:?]
	at com.github.quiltservertools.ticktools.TickToolsConfig.loadConfig(TickToolsConfig.java:49) ~[ticktools-1.0.0.jar:?]
	at com.github.quiltservertools.ticktools.TickTools.onServerStart(TickTools.java:23) ~[ticktools-1.0.0.jar:?]
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$0(ServerLifecycleEvents.java:37) ~[7379bcd2-9d77-4253-9590-9408b129a7a8.jar:?]
	at net.minecraft.server.MinecraftServer.handler$bbj000$beforeSetupServer(MixinMinecraftServer.java:5304) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MixinMinecraftServer.java:665) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MixinMinecraftServer.java:274) ~[intermediary-server.jar:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[10:17:53] [Server thread/ERROR]: This crash report has been saved to: Path\server\.\crash-reports\crash-2021-06-26_10.17.53-server.txt
[10:17:53] [Server thread/INFO]: Stopping server
[10:17:53] [Server thread/INFO]: Saving worlds
[10:17:53] [Server thread/ERROR]: Exception stopping the server
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_3218.method_8621()" because "☃" is null
	at net.minecraft.server.MinecraftServer.method_3723(MixinMinecraftServer.java:592) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_3782(MixinMinecraftServer.java:619) ~[intermediary-server.jar:?]
	at net.minecraft.class_3176.method_3782(MixinMinecraftDedicatedServer.java:584) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MixinMinecraftServer.java:729) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MixinMinecraftServer.java:274) ~[intermediary-server.jar:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by Genau6502** [comment]
This is a support question and should be asked on the discord - but you don't have the `maxRenderDistance` config value

**Comment by boasbakker** [comment]
I do have that

**Comment by boasbakker** [comment]
Also, when having the mod for the first time, the maxrenderdistance field isnt generatd, you need to typ it by hand. It still doesnt work, i have copied the exact config from the mod page, but with modified values. 

splitTickDistance = true
tickDistance = 16
itemDespawnTicks = 6000

[dynamic]
dynamicTickDistance = true
minTickDistance = 4
dynamicRenderDistance = true
minRenderDistance = 4
maxRenderDistance = 32

**Comment by boasbakker** [comment]
Also this is not a support question, it is a crash, a bug

**Comment by Genau6502** [comment]
Support should be on the discord - but I've pushed a commit fixing

Crashes are a support question
